name: WindSend Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch tags
        run: |
          git fetch --tags || true
          git tag --sort=-creatordate | head -n 1

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            windSend-rs/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: x86_64-apple-darwin, aarch64-apple-darwin
      - name: Set default Rust target
        run: |
          rustup show
      # - name: Set up JDK
      #   uses: actions/setup-java@v4
      #   with:
      #     java-version: "17"
      #     distribution: "adopt"
      # - name: Setup Ninja
      #   uses: seanmiddleditch/gha-setup-ninja@master
      # - name: Setup Flutter
      #   uses: subosito/flutter-action@v2
      #   with:
      #     channel: stable
      # - name: Print Flutter Info
      #   run: |
      #     flutter --version
      # # download flutter dependencies(to generate pubspec.lock)
      # - name: Download Flutter Dependencies
      #   working-directory: flutter/wind_send
      #   run: flutter pub get
      # cache flutter build
      # - uses: actions/cache@v4
      #   with:
      #     path: |
      #       flutter/wind_send/build/
      #       ~/.pub-cache
      #     key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-flutter-
      - name: Run Build Script
        env:
          CI_RUNNING: true # for build script
        working-directory: ./
        run: |
          chmod +x ./*.sh
          ./build_macos.sh

      - name: Archive artifacts
        id: build_archive
        uses: actions/upload-artifact@v4
        with:
          name: WindSend-Archives-macos
          path: |
            ./bin/*.zip
            ./bin/*.dmg
          if-no-files-found: error